[project]
name = "internyl-data-acquisition"
version = "1.0"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# This tells python that cli.py and the src folder are part of the project
packages = ["src"]
py-modules = ["cli"]

[project.scripts]
ida = "cli:main"
